/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[error].page': typeof import('./src/app/[error].page.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Index.page': typeof import('./src/app/index.page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SSvg: typeof import('./src/components/s-svg/index.vue')['default']
    'SuccessIndex.page': typeof import('./src/app/success/index.page.vue')['default']
    'TokenIndex.page': typeof import('./src/app/[token]/index.page.vue')['default']
  }
}
